## Defining situational awareness

In an outbreak, who needs to be aware of the situation, which specific situations, when, and why? At what resolution?

Analyse WHO DONs, public health (A/E/CDC) intelligence reports, dashboards…

Context: data science for Gaza response

data sources:
- https://disease-outbreaks-data.netlify.app/
https://github.com/jatorresmunguia/disease_outbreak_news 


## Eliciting policy preferences for evaluating forecasts

collabs: Kaitlyn, Sam, Liza, Seb, Kathryn
participants: ukhsa, LAs, ?

What makes a “good” outbreak forecast in routine public health intelligence?

Population: 

- Public health intelligence workforce

Pilot study: decision context 

- What decisions are made using forecasts?  
- What outbreak characteristics matter?

Full study: Discrete choice experiment to demonstrate preferences for forecast production

Set of alternative models \- variation across

- Model characteristics  
  - Performance   
  - Mechanistic interpretability  
  - Context specificity (disease, location)  
  - Known past performance  
- Modeller characteristics  
  - Trust in team producing  
  - Access to team producing (in house, external \- collaborator, external \- unknown)  
  - Ability to modify with additional data or alter assumptions  
  - …? identify from policy work  
- Outbreak characteristics  
  - Timing relative to peak  
  - Expected / unanticipated  
  - Population vulnerability

Preferences / beliefs about:

- Accuracy  
- Interpretability  
- Usefulness 

How much better would a single model have to be, to be chosen abovee the ensemble?

## Evaluating modelling in policy processes: a relational approach

Rationale: modelling using in policy is a tool for learning and prompting structured analysis of an uncertain situation

This has similarities to the use of talking therapy: supported navigation of uncertainty to support decision-making

Adopting measurement instruments from the working alliance model of psychological therapy effectiveness

- Positive alliance as predictor of successful intervention  
- Alliance model: Goal, task, and bond dimensions  
- [Development and validation of a revised short version of the working alliance inventory: Psychotherapy Research](https://www.tandfonline.com/doi/abs/10.1080/10503300500352500)   
- [The Therapeutic Alliance: The Fundamental Element of Psychotherapy \- PMC](https://pmc.ncbi.nlm.nih.gov/articles/PMC6493237/) 
