## Reporting guidelines for forecast evaluation: a standardised checklist

(“EPITOME \- Epidemiological tools for outbreak model evaluation”?)

Background

- Increasing activity developing and evaluating forecasts of infectious disease  
  - Evaluation important for model development and for understanding relative strengths between models / overall progress as a field  
  - Increasing technical development and adoption of evaluation methods (eg interval score, scoringutils, Hubs providing standardised evaluations)  
  - Many options for evaluation: target unit of the forecast (scale of aggregation), many different metrics, aggregation/transformation of forecast scores  
- Lack of standardised reporting of evaluation creates confusion and compromises comparisons  
  - No obvious guidance for using evaluation in individual model development   
  - Difficult to assess progress across the field: published literature \= systematic reviews, but these compare different metrics  
  - Hubs formed to create comparability, but Hubs are an extremely resource intense and not always appropriate  
- Need to consolidate this implicit consensus, make explicit, and support use outside of Hubs   
  - Support individual evaluation for model development and standardised reporting by traditional academic publication  
  - A lightweight option is a reporting checklist for publication  
  - EPIFORGE guidelines encouraged reporting standards for forecasting practice in general, without detail on forecast evaluation

Aims

- Develop reporting standard, add to equator network, encourage adoption 

Methods

- Rapid review / systematic analysis of methods / guidelines for reporting evaluation  
  - Set search criteria for papers reporting (infectious disease) forecasting  
    - Include papers reporting some quantitative evaluation  
  - Take random sample of X papers (assuming too many for systematic review)  
    - Sample balanced by epidemiological setting e.g. dengue/covid/flu…?  
  - Data extraction:   
    - Forecast targets: number of forecast, time horizon, target units  
    - Metric used: probabilistic etc, propriety, use of different metrics across targets  
- Delphi study for consensus on reporting items for evaluation   
  - Recruitment: balanced across different (health) forecasting fields  
    - Forecast producers  
    - Forecast users  
  - Question design  
  - Consensus process, interaction, revisions

Results

- Current practice: frequency / distribution of different methods  
- Consensus practice:

Discussion

- Innovation:    
- Impact: Professionalisation of modelling in line with other health sciences i.e. development of PRISMA guidelines for reporting RCTs  
- Expansion: develop training module as extension to NFIDD
