---
title: "Exploratory: Scoring epiforecast US covid forecasts"
output: html_document
---
<!--- Set up --->
```{r set-up, include=FALSE}
library(here)
library(dplyr)
library(readr)
library(tidyr)
library(tibble)
library(purrr)
library(ggplot2)
library(patchwork)
library(kableExtra)
theme_set(theme_classic())
knitr::opts_chunk$set(
  eval = TRUE, echo = FALSE,
  message = FALSE, warning = FALSE
)
```
<!--- Set up --->

Over 2020-2023, we published weekly forecasts of COVID-19 deaths in US states.

We built three forecasting models: a simple time series model, a model based on estimating the reproduction number (Rt) over time, and a model based on a case convolution.
Each week, we combined these three models into three separate ensembles: a mean, a median, and a quantile regression average (QRA). 
Each week we then reviewed all six forecasts for each state.
By default, we submitted the median ensemble to the Forecast Hub, but where this was judged to be implausible, we chose an alternative model or ensemble.
At the same time we were continuously building and modifying model code.

All forecasts submitted to the Hub were evaluated independently by the Hub team.
However, these only cover the single forecast submitted. 
Our open, documented commit history provides a richer dataset that links model development, selection by human judgement, with resulting accuracy.
We have not published any formal evaluation of this forecasting work. 

I can see several directions for evaluation:

- Forecasts versus reality: how accurate were predicted counts against final reported data?
  - How about against real-time data?
  - How accurate were estimates of the reproduction number compared to the most recent 'best' model estimates?
- Humans versus models: how accurate was the human judgement approach to model selection? 
  - where the median ensemble was judged implausible, when was this the right call, and how much more accurate was the resulting submission compared to the default? 
  - were there similarities in the types of situations where human judgement was used and more accurate? 
  - how did the human judgement approach compare to an automated rule-based approach (e.g. if median ensemble forecasted a large increase, choose an alternative)?
- Human versus human: how did model development impact accuracy?
  - Model development could be measured as volume of code commits, or categorically between substantive changes identified from qualitative review of commit history
- Model versus model: evaluate marginal performance relative to other models conributing to the overall US Hub ensemble (e.g. LOMO or PAR metrics)

### Analysis plan
