---
title: "Exploratory: Scoring epiforecast covid forecasts"
output: html_document
---
<!--- Set up --->
```{r set-up, include=FALSE}
library(here)
library(dplyr)
library(readr)
library(tidyr)
library(tibble)
library(purrr)
library(ggplot2)
library(patchwork)
library(kableExtra)
theme_set(theme_classic())
knitr::opts_chunk$set(
  eval = TRUE, echo = FALSE,
  message = FALSE, warning = FALSE
)
```
<!--- Set up --->

Over 2020-2025, we published frequent updates to forecasts of COVID-19 globally, for cases, and where available, hospitalisations and deaths. 

To do this, we used an approach based on estimating the reproduction number (Rt) over time, allowing us to estimate infections and subsequent syndromic indicators.
We continuously published the forecasts while building and modifying model code.
This was built openly as EpiNow and subsequently EpiNow2 (from August 2020). 

We have some formal and some anecdotal evidence that these were used widely in public health settings for decision-making.
We have not published any formal evaluation of this forecasting work. 

I can see several directions for evaluation:

- Forecasts versus data: how accurate were predicted counts against final reported data? against real-time data? how accurate were estimates of the reproduction number compared to the most recent 'best' model estimates? how similar were reproduction number estimates from alternative data sources (e.g. deaths compares to cases), given these should index back to the same underlying transmission?
- Model development over time: how did model development impact accuracy? Development could be measured as volume of code commit history, or categorically between release dates as a meaningful marker of substantive change
- Public health use: trace citations to software and website, in academic literature and grey literature (e.g. Overton); website analytics; code interactions and package use

The latter would be best supported with some qualitative work to unpack [why](evaluation.qmd).

### Load data
